//
//  languageNew.h
//  shinelink
//
//  Created by sky on 16/5/3.
//  Copyright © 2016年 sky. All rights reserved.
//

#ifndef languageNew_h
#define languageNew_h



#pragma mark - 登陆
#define  root_liji_tiyan       NSLocalizedString(@"立即体验", nil)
#define  root_next_go        NSLocalizedString(@"下一步", nil)
#define  root_finish        NSLocalizedString(@"完成", nil)
#define  root_server_error        NSLocalizedString(@"服务器错误", nil)
#define  root_paiZhao        NSLocalizedString(@"拍照", nil)
#define  root_xiangkuang_xuanQu        NSLocalizedString(@"从相册选取", nil)
#define  root_cancel        NSLocalizedString(@"取消", nil)
#define  root_ALET        NSLocalizedString(@"警告", nil)
#define  root_OK        NSLocalizedString(@"确定", nil)
#define  root_del        NSLocalizedString(@"删除", nil)
#define  root_saomiao_jieguo       NSLocalizedString(@"扫描结果", nil)
#define  root_set       NSLocalizedString(@"配置", nil)
#define  root_kongzhi_Alert      NSLocalizedString(@"控制提示", nil)
#define  root_tianjia_wenti_Alert      NSLocalizedString(@"添加问题提示", nil)
#define  root_kongzhi_mima      NSLocalizedString(@"控制密码", nil)
#define  root_back      NSLocalizedString(@"返回", nil)
#define  root_stop_config      NSLocalizedString(@"停止配置", nil)
#define  root_zhuce_shibai      NSLocalizedString(@"5注册失败", nil)

#define  root_tuichu_zhanghu     NSLocalizedString(@"是否退出当前账户", nil)
//登陆
#define  root_yongHuMing_mima_cuowu        NSLocalizedString(@"用户名密码错误 ", nil)
#define  root_yongHuMing_mima_weikong        NSLocalizedString(@"用户名密码为空", nil)

#define root_Enter_your_username       NSLocalizedString(@"Enter your username", @"Enter your username")
#define root_Enter_your_pwd       NSLocalizedString(@"Enter your pwd", @"Enter your pwd")
#define root_forget_pwd       NSLocalizedString(@"忘记密码", nil)
#define root_register       NSLocalizedString(@"注册", nil)
#define root_log_in      NSLocalizedString(@"登陆", nil)
#define root_demo_test      NSLocalizedString(@"体验馆", nil)
#define  root_Alet_user        NSLocalizedString(@"温馨提示 ", nil)
#define  root_Alet_user_messge        NSLocalizedString(@"请输入用户名 ", nil)
#define  root_Alet_user_pwd        NSLocalizedString(@"请输入密码 ", nil)
#define  root_old_pwd        NSLocalizedString(@"原密码 ", nil)

#define  root_demo_Alert        NSLocalizedString(@"浏览用户禁止操作", nil)
#define  root_huoqu_wufuqi_dizhi        NSLocalizedString(@"获取服务器地址", nil)

//注册

#define  root_peizhi_chenggong        NSLocalizedString(@"配置成功", nil)
#define  root_country        NSLocalizedString(@"国家", nil)
#define  root_country_alet        NSLocalizedString(@"点击选择国家", nil)
#define  root_country_kong        NSLocalizedString(@"请选择国家和城市", nil)
#define  root_country_huoQu        NSLocalizedString(@"请再次进入页面获取国家列表", nil)
#define  root_xuanzhe_country        NSLocalizedString(@"选择国家", nil)
#define  root_sousuo        NSLocalizedString(@"搜索", nil)


#define  root_yongHuMing        NSLocalizedString(@"用户名", nil)
#define  root_Mima        NSLocalizedString(@"密码", nil)
#define  root_chongFu_miMa        NSLocalizedString(@"重复密码", nil)
#define  root_chongFu_shuRu_miMa       NSLocalizedString(@"重复输入密码", nil)
#define  root_dianzZiYouJian        NSLocalizedString(@"电子邮箱", nil)
#define  root_DianHua        NSLocalizedString(@"联系电话", nil)
#define  root_daiLiShangBianHao        NSLocalizedString(@"代理商编号", nil)
#define  root_shuRu_daiLiShangBianHao        NSLocalizedString(@"输入代理商编号", nil)
#define  root_xiangTong_miMa        NSLocalizedString(@"请输入相同的密码", nil)
#define  root_daYu_san       NSLocalizedString(@"用户名必须大于3位", nil)
#define  root_daYu_liu        NSLocalizedString(@"密码必须大于6位", nil)
#define  root_weiZhi       NSLocalizedString(@"位置", nil)
#define  root_weiZhi_tiShi        NSLocalizedString(@"点击获取城市和经纬度", nil)
#define root_Enter_email       NSLocalizedString(@"Enter email", @"Enter email")
#define root_Enter_phone_number       NSLocalizedString(@"Enter phone number", @"Enter phone number")
#define root_Networking      NSLocalizedString(@"Networking Timeout", @"Networking Timeout")
#define root_Yes       NSLocalizedString(@"Yes", @"Yes")
#define  root_caiJiQi         NSLocalizedString(@"请输入采集器序列号", nil)
#define  root_caiJiQi_zhengque        NSLocalizedString(@"请输入正确采集器序列号", nil)
#define  root_jiaoYanMa       NSLocalizedString(@"请输入采集器校验码", nil)
#define  root_jiaoYanMa_zhengQue       NSLocalizedString(@"请输入正确采集器校验码", nil)
#define  root_erWeiMa       NSLocalizedString(@"扫描条形码", nil)
#define  root_weiZhi       NSLocalizedString(@"位置", nil)

#define  root_chaoChu_shuLiang       NSLocalizedString(@"超出版本限制注册用户数量", nil)
#define  root_fuWuQi_cuoWu      NSLocalizedString(@"服务器错误", nil)
#define  root_zhuCe_cuoWu       NSLocalizedString(@"注册错误", nil)
#define  root_caijiqi_cuowu       NSLocalizedString(@"采集器序列号或校验码错误", nil)
#define  root_dailishang_cuowu       NSLocalizedString(@"代理商编码错误", nil)
#define  root_zhuCe_chengGong      NSLocalizedString(@"注册成功", nil)
#define  root_yongHu_yi_shiYong       NSLocalizedString(@"用户名已被使用", nil)

#define  root_zhaohui_mima      NSLocalizedString(@"找回密码", nil)
#define  root_tongGuo_yonghuMing       NSLocalizedString(@"通过用户名", nil)
#define  root_tongGuo_xuLieHao       NSLocalizedString(@"通过序列号", nil)
#define  root_zhengQueDe_yonghuMing       NSLocalizedString(@"请输入正确的用户名", nil)
#define  root_youJian_shiBai       NSLocalizedString(@"发送邮件失败", nil)
#define  root_zhaoBuDao_yongHu       NSLocalizedString(@"不能找到用户名", nil)
#define  root_peiZhi_sheBei      NSLocalizedString(@"配置设备", nil)
#define  root_jiaoYanMa_cuoWu      NSLocalizedString(@"校验码错误", nil)


#pragma mark - 设备
//设备
#define  root_device        NSLocalizedString(@"设备", nil)
#define  root_shiFan_dianZhan        NSLocalizedString(@"示范电站", nil)
#define  root_niBianQi        NSLocalizedString(@"逆变器", nil)
#define  root_chuNengJi        NSLocalizedString(@"储能机", nil)
#define  root_chongDianZhuang        NSLocalizedString(@"充电桩", nil)
#define  root_gongLvTiaoJieQi       NSLocalizedString(@"功率调节器", nil)
#define  root_wei_LianJie       NSLocalizedString(@"未连接", nil)
#define  root_tianJia_sheBei       NSLocalizedString(@"添加设备", nil)
#define  root_xiTong_CuoWu      NSLocalizedString(@"系统错误", nil)
#define  root_shanChu_chengGong      NSLocalizedString(@"删除成功", nil)
#define root_caiJiQi_leiBiao  NSLocalizedString(@"采集器列表", nil)

#define root_Add_Plant       NSLocalizedString(@"Add Plant", @"Add Plant")
#define root_Remove_Station       NSLocalizedString(@"Remove Station", @"Remove Station")
#define root_Upload_Picture       NSLocalizedString(@"Upload Picture", @"Upload Picture")
#define root_Cancel       NSLocalizedString(@"Cancel", @"Cancel")

#define root_xitong_cuoWu       NSLocalizedString(@"系统错误", nil)
#define root_xiuGai_chengGong       NSLocalizedString(@"修改成功", nil)
#define root_yi_peiZhi       NSLocalizedString(@"已配置设备", nil)
#define root_wei_peiZhi       NSLocalizedString(@"未配置设备", nil)
#define root_ri_dianLiang       NSLocalizedString(@"日电量:", nil)
#define root_dianChi_baifenBi       NSLocalizedString(@"电池百分比:", nil)
#define root_bianJi       NSLocalizedString(@"编辑", nil)
#define root_zhiDing       NSLocalizedString(@"置顶 ", nil)

#define root_dengDai       NSLocalizedString(@"等待 ", nil)
#define root_zhengChang       NSLocalizedString(@"正常 ", nil)
#define root_cuoWu      NSLocalizedString(@"故障", nil)
#define root_duanKai       NSLocalizedString(@"断开", nil)
#define root_xianZhi       NSLocalizedString(@"闲置 ", nil)
#define root_chongDian       NSLocalizedString(@"充电 ", nil)
#define root_fangDian       NSLocalizedString(@"放电 ", nil)
#define root_xianQing       NSLocalizedString(@"详情 ", nil)
#define root_gongLv       NSLocalizedString(@"功率:", nil)

#define root_bieMing       NSLocalizedString(@"请输入设备别名", nil)
#define root_xiugai_bieming       NSLocalizedString(@"修改别名", nil)
#define root_xiugai_touxiang       NSLocalizedString(@"修改头像", nil)
#define root_xiugai_shebei      NSLocalizedString(@"删除设备", nil)

//设备二级
#define root_kongzhi      NSLocalizedString(@"控制", nil)
#define root_canshu      NSLocalizedString(@"参数", nil)
#define root_shuju      NSLocalizedString(@"数据", nil)
#define root_rizhi      NSLocalizedString(@"日志", nil)

//逆变器二级
#define root_ri_gonglv_zoushitu     NSLocalizedString(@"日功率走势图", nil)
#define root_NBQ_ri_dianliang      NSLocalizedString(@"日电量", nil)
#define root_dangqian_gonglv     NSLocalizedString(@"当前功率", nil)
#define root_NBQ_zong_dianliang      NSLocalizedString(@"总电量", nil)
#define root_NBQ_ri_fadianliang      NSLocalizedString(@"日发电量", nil)
#define root_NBQ_youxiao_gonglv     NSLocalizedString(@"设置有效功率", nil)
#define root_NBQ_wuxiao_gonglv      NSLocalizedString(@"设置无功功率", nil)
#define root_NBQ_PF      NSLocalizedString(@"设置PF值", nil)
#define root_NBQ_shijian     NSLocalizedString(@"设置逆变器时间:", nil)
#define root_NBQ_shifou_kaiqi      NSLocalizedString(@"是否确定开启逆变器", nil)
#define root_NBQ_shifou_guanbi     NSLocalizedString(@"是否确定关闭逆变器", nil)
#define root_NBQ_kaiguan     NSLocalizedString(@"设置逆变器开关机", nil)
#define root_NBQ_xunliehao     NSLocalizedString(@"序列号:", nil)
#define root_NBQ_leixing     NSLocalizedString(@"类型:", nil)
#define root_NBQ_shijianhao     NSLocalizedString(@"事件号:", nil)
#define root_NBQ_biaoshi     NSLocalizedString(@"标识:", nil)


//储能机二级
#define root_ri_fangdianliang      NSLocalizedString(@"日放电量", nil)
#define root_zong_fangdianliang     NSLocalizedString(@"总放电量", nil)
#define root_dianchi      NSLocalizedString(@"电池百分比(%)", nil)

#define root_CNJ_kaiguan      NSLocalizedString(@"设置储能机开关机", nil)
#define root_CNJ_SOC      NSLocalizedString(@"锂电池SOC下限设定", nil)
#define root_CNJ_shijian     NSLocalizedString(@"设置储能机时间", nil)
#define root_CNJ_fangdian_kaiguan      NSLocalizedString(@"强制放电使能", nil)
#define root_CNJ_fangdian_shijian       NSLocalizedString(@"强制放电时间段", nil)
#define root_CNJ_SP      NSLocalizedString(@"设置输入SP的组串电压", nil)
#define root_CNJ_kaiji      NSLocalizedString(@"开机", nil)
#define root_CNJ_guanji      NSLocalizedString(@"关机", nil)
#define root_CNJ_SOC_xia      NSLocalizedString(@"锂电池SOC下限设定", nil)
#define root_CNJ_shijian_she      NSLocalizedString(@"设置储能机时间:", nil)
#define root_CNJ_fangjian_shineng      NSLocalizedString(@"强制放电使能:", nil)
#define root_kai     NSLocalizedString(@"开", nil)
#define root_guan      NSLocalizedString(@"关", nil)
#define root_CNJ_fangdian_shijianduan     NSLocalizedString(@"强制放电时间段:", nil)
#define root_zhi      NSLocalizedString(@"至", nil)
#define root_CNJ_kailu_dianya      NSLocalizedString(@"开路电压(300~500V):", nil)
#define root_CNJ_MPP     NSLocalizedString(@"MPP电压:", nil)

#define root_CNJ_fuwuqi_cuowu    NSLocalizedString(@"所属服务器错误", nil)
#define root_CNJ_xuliehao_kong    NSLocalizedString(@"序列号为空", nil)
#define root_CNJ_buzaixian     NSLocalizedString(@"不在线", nil)
#define root_CNJ_caijiqi_buzai     NSLocalizedString(@"采集器不在线", nil)
#define root_CNJ_leixing_buzai     NSLocalizedString(@"参数类型不存在", nil)
#define root_CNJ_canshu_kong     NSLocalizedString(@"参数为空", nil)
#define root_CNJ_canshu_buzai_fanwei     NSLocalizedString(@"参数不在范围内", nil)
#define root_CNJ_shijian_budui     NSLocalizedString(@"时间参数不正确", nil)
#define root_CNJ_canshu_chenggong     NSLocalizedString(@"参数设置成功", nil)
#define root_CNJ_shifou_kaiqi_CNJ     NSLocalizedString(@"是否确定开启储能机", nil)
#define root_CNJ_shifou_guanbi_CNJ      NSLocalizedString(@"是否确定关闭储能机", nil)
#define root_Demo_tishi      NSLocalizedString(@"示范设备暂时不开放此功能,请安装真实产品使用此功能.", nil)


#define root_xinghao     NSLocalizedString(@"型号", nil)
#define root_xuleihao      NSLocalizedString(@"序列号", nil)
#define root_duankou     NSLocalizedString(@"端口", nil)
#define root_bieming      NSLocalizedString(@"别名", nil)
#define root_CNJ_eDing_gonglv      NSLocalizedString(@"额定功率", nil)
#define root_gujian_banben      NSLocalizedString(@"固件版本", nil)
#define root_shuxing      NSLocalizedString(@"属性", nil)
#define root_moshi     NSLocalizedString(@"模式", nil)

//数据采集器/编辑采集器
#define root_zubie     NSLocalizedString(@"组别", nil)
#define root_shebei_leixing    NSLocalizedString(@"设备类型", nil)
#define root_data_update_interval       NSLocalizedString(@"数据更新时间", nil)


#define root_tianjia_chucuo      NSLocalizedString(@"添加出错", nil)
#define root_meiyou_quanxian      NSLocalizedString(@"没有权限", nil)
#define root_xuliehao_cuowu      NSLocalizedString(@"采集器序列号错误", nil)
#define root_zongti_shuliang_chaochu_xianzhi      NSLocalizedString(@"总体采集器数量超出限制", nil)
#define root_danGe_shuliang_chaochu_xianzhi      NSLocalizedString(@"单个电站采集器数量超出限制", nil)
#define root_xuliehao_yijing_cunzai      NSLocalizedString(@"采集器序列号已经存在", nil)
#define root_xuliehao_jiaoyanMa_bupipei      NSLocalizedString(@"序列号与校验码不匹配", nil)
#define root_shebei_tianjia_chenggong      NSLocalizedString(@"设备添加成功", nil)

#define root_CJQ_tianjia      NSLocalizedString(@"添加采集器", nil)
#define root_CJQ_bianji      NSLocalizedString(@"编辑采集器", nil)
#define root_CJQ_shanchu     NSLocalizedString(@"删除采集器", nil)
#define root_CJQ_peizhi      NSLocalizedString(@"配置采集器", nil)


#define root_Add       NSLocalizedString(@"Add", @"Add")
#define root_aliases       NSLocalizedString(@"aliases", @"aliases")
#define root_datalog_sn       NSLocalizedString(@"datalog sn", @"datalog sn")
#define root_group       NSLocalizedString(@"group", @"group")
#define root_device_type       NSLocalizedString(@"device type", @"device type")

#define root_Add       NSLocalizedString(@"Add", @"Add")
#define root_Modified       NSLocalizedString("Modified", @"Modified")
#define root_Delete       NSLocalizedString(@"Delete", @"Delete")
#define root_Aliases_can_not_be_empty       NSLocalizedString(@"Aliases can not be empty", @"Aliases can not be empty")
#define root_Successfully_modified       NSLocalizedString(@"Successfully modified", @"Successfully modified")
#define root_Modification_fails       NSLocalizedString(@"Modification fails", @"Modification fails")
#define root_Successfully_deleted       NSLocalizedString(@"Successfully deleted", @"Successfully deleted")
#define root_Delete_failed       NSLocalizedString(@"Delete failed", @"Delete failed")
#define root_Added_successfully       NSLocalizedString(@"Added successfully", @"Added successfully")

//添加数据采集器
#define root_Add       NSLocalizedString(@"Add", @"Add")
#define root_Enter_DatalogSN       NSLocalizedString(@"Enter DatalogSN", @"Enter DatalogSN")
#define root_Datalog_Valicode       NSLocalizedString(@"Datalog Valicode", @"Datalog Valicode")
#define root_Insert_true_datalog_sn       NSLocalizedString(@"Insert true datalog sn", @"Insert true datalog sn")
#define root_Datalog_verification_code_is_incorrect       NSLocalizedString(@"Datalog verification code is incorrect", @"Datalog verification code is incorrect")
#define root_Datalog_verification_code_is_incorrect       NSLocalizedString(@"Datalog verification code is incorrect", @"Datalog verification code is incorrect")
#define root_Added_Successfully       NSLocalizedString(@"Added Successfully", @"Added Successfully")
#define root_Add_Failed       NSLocalizedString(@"Add Failed", @"Add Failed")
#define root_Insert_datalog_code       NSLocalizedString(@"Insert datalog code", @"Insert datalog code")

//电站列表
#define root_Plant_List       NSLocalizedString(@"Plant List", @"Plant List")
#define root_Today_Energy       NSLocalizedString(@"Today Energy", @"Today Energy")
#define root_Total_Energy       NSLocalizedString(@"Total Energy", @"Total Energy")
#define root_Current_Power       NSLocalizedString(@"Current Power", @"Current Power")
#define root_Gains       NSLocalizedString(@"Gains", @"Gains")
#define root_Percentage       NSLocalizedString(@"Percentage", @"Percentage")
#define root_Storage_Status       NSLocalizedString(@"Storage Status", @"Storage Status")
#define root_Charge_Power       NSLocalizedString(@"Charge Power", @"Charge Power")
#define root_Discharge_Power       NSLocalizedString(@"Discharge Power", @"Discharge Power")
#define root_Add_Plant       NSLocalizedString(@"Add Plant", @"Add Plant")
#define root_Remove_Station       NSLocalizedString(@"Remove Station", @"Remove Station")
#define root_Upload_Picture       NSLocalizedString(@"Upload Picture", @"Upload Picture")
#define root_Setting_Station_Map       NSLocalizedString(@"Setting Station Map", @"Setting Station Map")
#define root_Installation_Information       NSLocalizedString(@"Installation Information", @"Installation Information")
#define root_plant_name       NSLocalizedString(@"plant name", @"plant name")
#define root_instal_date       NSLocalizedString(@"instal date", @"instal date")
#define root_company       NSLocalizedString(@"company", @"company")
#define root_power       NSLocalizedString(@"power", @"power")
#define root_Next       NSLocalizedString(@"Next", @"Next")

//电站详情
#define root_Plant_Detail       NSLocalizedString(@"Plant Detail", @"Plant Detail")
#define root_DAY       NSLocalizedString(@"DAY", @"DAY")
#define root_MONTH       NSLocalizedString(@"MONTH", @"MONTH")
#define root_YEAR       NSLocalizedString(@"YEAR", @"YEAR")
#define root_TOTAL       NSLocalizedString(@"TOTAL", @"TOTAL")
#define root_Daily_Returns       NSLocalizedString(@"Daily Returns", @"Daily Returns")
#define root_Daily_Electricity       NSLocalizedString(@"Daily Electricity", @"Daily Electricity")
#define root_Earnings       NSLocalizedString(@"Earnings", @"Earnings")
#define root_Month_energy       NSLocalizedString(@"Month energy", @"Month energy")
#define root_Earnings       NSLocalizedString(@"Earnings", @"Earnings")
#define root_Year_energy       NSLocalizedString(@"Year energy", @"Year energy")
#define root_Earnings       NSLocalizedString(@"Earnings", @"Earnings")
#define root_Total_energy       NSLocalizedString(@"Total energy", @"Total energy")
#define root_Powre       NSLocalizedString(@"Powre", @"Power")
#define root_Plant_Overview       NSLocalizedString(@"Plant Overview", @"Plant Overview")
#define root_Device_List       NSLocalizedString(@"Device List", @"Device List")
#define root_Event_List       NSLocalizedString(@"Event List", @"Event List")
#define root_Map       NSLocalizedString(@"Map", @"Map")
#define root_Voltage      NSLocalizedString(@"Voltage", @"Voltage")
#define root_Electron_flow      NSLocalizedString(@"Electron flow", @"Electron flow")

//详情（逆变器）
#define root_PV_POWER       NSLocalizedString(@"PV POWER", @"PV POWER")
#define root_PV1_VOLTAGE       NSLocalizedString(@"PV1 VOLTAGE", @"PV1 VOLTAGE")
#define root_PV1_ELEC_CURRENT       NSLocalizedString(@"PV1 ELEC-CURRENT", @"PV1 ELEC-CURRENT")
#define root_PV2_VOLTAGE       NSLocalizedString(@"PV2 VOLTAGE", @"PV2 VOLTAGE")
#define root_PV2_ELEC_CURRENT       NSLocalizedString(@"PV2 ELEC-CURRENT", @"PV2 ELEC-CURRENT")
#define root_R_PHASE_POWER       NSLocalizedString(@"R-PHASE POWER", @"R-PHASE POWER")
#define root_S_PHASE_POWER       NSLocalizedString(@"S-PHASE POWER", @"S-PHASE POWER")
#define root_T_PHASE_POWER       NSLocalizedString(@"T-PHASE POWER", @"T-PHASE POWER")
#define root_POWER       NSLocalizedString(@"POWER", @"POWER")
#define root_Energy       NSLocalizedString(@"Energy", @"Energy")
#define root_shuchu_gonglv       NSLocalizedString(@"1输出功率", nil)

//详情（储能机）
#define root_CHARGING_POWER       NSLocalizedString(@"CHARGING POWER", @"CHARGING POWER")
#define root_DISCHARGING_POWER       NSLocalizedString(@"DISCHARGING POWER", @"DISCHARGING POWER")
#define root_INPUT_VOLTAGE       NSLocalizedString(@"INPUT VOLTAGE", @"INPUT VOLTAGE")
#define root_INPUT_CURRENT       NSLocalizedString(@"INPUT CURRENT", @"INPUT CURRENT")
#define root_USER_SIDE_POWER       NSLocalizedString(@"USER-SIDE POWER", @"USER-SIDE POWER")
#define root_GRID_SIDE_POWER       NSLocalizedString(@"GRID-SIDE POWER", @"GRID-SIDE POWER")

#define root_MONTH_BATTERY_CHARGE     NSLocalizedString(@"MONTH BATTERY CHARGE" , @"MONTH BATTERY CHARGE")
#define root_MONTHLY_CHARGED     NSLocalizedString(@"MONTHLY CHARGED", @"MONTHLY CHARGED")
#define root_MONTHLY_DISCHARGED     NSLocalizedString(@"MONTHLY DISCHARGED", @"MONTHLY DISCHARGED")
#define root_YEAR_BATTERY_CHARGE     NSLocalizedString(@"YEAR BATTERY CHARGE", @"YEAR BATTERY CHARGE")
#define root_YEAR_CHARGED     NSLocalizedString(@"YEAR CHARGED", @"YEAR CHARGED")
#define root_YEAR_DISCHARGED     NSLocalizedString(@"YEAR DISCHARGED", @"YEAR DISCHARGED")
#define root_TOTAL_BATTERY_CHARGE     NSLocalizedString(@"TOTAL BATTERY CHARGE", @"TOTAL BATTERY CHARGE")
#define root_TOTAL_CHARGED     NSLocalizedString(@"TOTAL CHARGED", @"TOTAL CHARGED")
#define root_TOTAL_DISCHARGED     NSLocalizedString(@"TOTAL DISCHARGED", @"TOTAL DISCHARGED")


#pragma mark - 能源

#define  root_energy_title        NSLocalizedString(@"能源", nil)
#define  root_energy        NSLocalizedString(@"能源分析", nil)
#define  root_energy_Smart       NSLocalizedString(@"智能能源", nil)
#define  root_energy_jiating_yongdian       NSLocalizedString(@"家庭用电量", nil)
#define  root_energy_jiating_shebei       NSLocalizedString(@"家庭用电设备", nil)
#define  root_energy_guangfu_dianliang      NSLocalizedString(@"光伏电量", nil)
#define  root_energy_chuneng_dianliang       NSLocalizedString(@"储能电量", nil)
#define  root_energy_chuneng_yue       NSLocalizedString(@"月:", nil)
#define  root_energy_chuneng_zuishengdian       NSLocalizedString(@"最省电:", nil)
#define  root_energy_chuneng_zuihaodian       NSLocalizedString(@"最耗电:", nil)
#define  root_energy_chuneng_ri       NSLocalizedString(@"日:", nil)

#define  root_energy_tiaodu_youxian      NSLocalizedString(@"能源调度优先级设置", nil)
#define  root_energy_liandong_shezhi       NSLocalizedString(@"智能联动设置", nil)
#define  root_energy_dianjia_shezhi       NSLocalizedString(@"峰谷电价设置", nil)
#define  root_energy_dongzuo_shineng       NSLocalizedString(@"峰谷段动作使能", nil)
#define  root_energy_kongzhi_youxian       NSLocalizedString(@"控制优先级设置", nil)
#define  root_energy_lingonglv_shineng       NSLocalizedString(@"光伏零功率输出使能", nil)
#define  root_energy_wenxin_tishi       NSLocalizedString(@"温馨提示", nil)
#define  root_energy_houxun_kaifang       NSLocalizedString(@"智能能源功能后续开放", nil)
#define  root_zhibao_chaxun_tishi       NSLocalizedString(@"质保查询功能后续开放", nil)


#define  root_energy_jiating_yongdian_zhanbi       NSLocalizedString(@"家庭用电占比(Demo)", nil)
#define  root_energy_dianbinxiang       NSLocalizedString(@"电冰箱", nil)
#define  root_energy_weibolu       NSLocalizedString(@"微波炉", nil)
#define  root_energy_kongtiao       NSLocalizedString(@"空调", nil)
#define  root_energy_dianshiji       NSLocalizedString(@"电视机", nil)
#define  root_energy_xiyiji       NSLocalizedString(@"洗衣机", nil)
#define  root_energy_reshuiqi       NSLocalizedString(@"热水器", nil)
#define  root_energy_fadianliang       NSLocalizedString(@"发电量", nil)
#define  root_energy_fangdianliang       NSLocalizedString(@"放电量", nil)
#define  root_energy_zuidazhi       NSLocalizedString(@"最大值", nil)
#define  root_energy_pingjunzhi       NSLocalizedString(@"平均值", nil)

#pragma mark - 服务
#define  root_service        NSLocalizedString(@"服务", nil)
#define  root_ME_wenti       NSLocalizedString(@"我的问题", nil)
#define  root_ME_changjian_wenti        NSLocalizedString(@"常见问题", nil)
#define  root_ME_kefu        NSLocalizedString(@"客户服务", nil)
#define  root_ME_zhibao        NSLocalizedString(@"质保查询", nil)
#define  root_ME_zengzhi      NSLocalizedString(@"增值业务", nil)
#define  root_ME_gengduo       NSLocalizedString(@"更多产品", nil)

#define  root_ME_tijiao_wenti       NSLocalizedString(@"提交问题", nil)
#define  root_ME_biaoti       NSLocalizedString(@"标题:", nil)
#define  root_ME_wenti_leixing      NSLocalizedString(@"问题类型:", nil)
#define  root_ME_neirong      NSLocalizedString(@"内容:", nil)
#define  root_ME_biaoti_shuru      NSLocalizedString(@"请输入标题", nil)
#define  root_ME_wenti_leixing_xuanzhe      NSLocalizedString(@"请选择问题类型", nil)
#define  root_ME_xuliehao_shuru      NSLocalizedString(@"请输入序列号", nil)
#define  root_ME_fujian      NSLocalizedString(@"附件:", nil)
#define  root_ME_shangchuan_tupian      NSLocalizedString(@"请选择要上传图片", nil)
#define  root_ME_shuru_leirong      NSLocalizedString(@"请输入内容", nil)
#define  root_ME_tianjia_chenggong     NSLocalizedString(@"添加成功", nil)
#define  root_ME_tianjia_shibai      NSLocalizedString(@"添加错误", nil)

#define  root_ME_nibianqi_guzhan      NSLocalizedString(@"逆变器故障", nil)
#define  root_ME_chunengji_guzhan      NSLocalizedString(@"储能机故障", nil)
#define  root_ME_ruanjian_jianyi      NSLocalizedString(@"监控系统问题", nil)
#define  root_ME_ruanjian_guzhan      NSLocalizedString(@"功能建议", nil)
#define  root_ME_qita_shebei_guzhan      NSLocalizedString(@"问题咨询", nil)
#define  root_ME_qita_wenti      NSLocalizedString(@"其他问题", nil)

#define  root_ME_wenti_liebiao      NSLocalizedString(@"问题列表", nil)
#define  root_ME_wei_chuli     NSLocalizedString(@"未处理", nil)
#define  root_ME_zhengzai_chuli      NSLocalizedString(@"正在处理", nil)
#define  root_ME_yi_chuli     NSLocalizedString(@"已处理", nil)
#define  root_ME_shanchu_liebiao    NSLocalizedString(@"删除列表", nil)
#define  root_ME_huifu_jilu    NSLocalizedString(@"回复记录", nil)
#define  root_ME_huifu   NSLocalizedString(@"回 复", nil)
#define  root_ME_chakan_tupian    NSLocalizedString(@"查看图片", nil)
#define  root_ME_gaisu    NSLocalizedString(@"概述", nil)
#define  root_ME_canshu    NSLocalizedString(@"参数", nil)
#define  root_ME_you  NSLocalizedString(@"有", nil)
#define  root_ME_meiyou    NSLocalizedString(@"没有", nil)
#define  root_ME_youwu_zhibao    NSLocalizedString(@"有无质保:", nil)
#define  root_ME_chuchang_shijian    NSLocalizedString(@"出厂时间:", nil)
#define  root_ME_daoqi_shijian    NSLocalizedString(@"到期时间:", nil)
#define root_zhibao_xunliehao     NSLocalizedString(@"序列号码:", nil)



#pragma mark - 我

#define   root_ME        NSLocalizedString(@"我", nil)
#define   root_WO_zhiliao_guanli        NSLocalizedString(@"资料管理", nil)
#define   root_WO_xitong_shezhi       NSLocalizedString(@"电站设置", nil)
#define   root_WO_xiaoxi_zhongxin      NSLocalizedString(@"消息中心", nil)
#define   root_WO_guanyu        NSLocalizedString(@"关于", nil)
#define   root_WO_xieyi        NSLocalizedString(@"用户协议", nil)
#define   root_WO_kefu_dianhua        NSLocalizedString(@"客服电话", nil)
#define   root_WO_jiancha_gengxin       NSLocalizedString(@"检查更新", nil)
#define   root_WO_zuixin_banben      NSLocalizedString(@"最新版本为", nil)
#define   root_WO_shifou_gengxin       NSLocalizedString(@"是否更新", nil)
#define   root_WO_shi_zuixin_banben       NSLocalizedString(@"您使用的是最新版本", nil)
#define   root_WO_zanbu       NSLocalizedString(@"暂不", nil)
#define   root_WO_liji_gengxin       NSLocalizedString(@"立即更新", nil)
#define   root_WO_pingguo_fuwuqi_shibai      NSLocalizedString(@"请求苹果服务器失败", nil)
#define   root_WO_xiugai_mima      NSLocalizedString(@"修改密码", nil)
#define   root_WO_xiugai_shoujihao      NSLocalizedString(@"修改手机号", nil)
#define   root_WO_xiugai_youxiang      NSLocalizedString(@"修改邮箱", nil)
#define   root_WO_xiugai_dailishang     NSLocalizedString(@"修改代理商编号", nil)
#define   root_WO_zhuxiao_zhanhao     NSLocalizedString(@"注销账号", nil)
#define   root_WO_shuru_shoujihao     NSLocalizedString(@"输入手机号", nil)
#define   root_WO_shuru_youxiang     NSLocalizedString(@"输入邮箱地址", nil)
#define   root_WO_shuru_dailishang    NSLocalizedString(@"输入代理商编号", nil)
#define   root_WO_yonghu_bucunzai     NSLocalizedString(@"用户不存在", nil)
#define   root_WO_anzhuang     NSLocalizedString(@"安装信息", nil)
#define   root_WO_dili     NSLocalizedString(@"地理信息", nil)
#define   root_WO_zijin     NSLocalizedString(@"资金收益", nil)
#define   root_WO_tupian    NSLocalizedString(@"电站图片", nil)
#define   root_WO_buneng_weikong    NSLocalizedString(@"不能为空", nil)
#define   root_WO_chengshi    NSLocalizedString(@"城市", nil)
#define   root_WO_shiqu    NSLocalizedString(@"时区", nil)
#define   root_WO_jingdu    NSLocalizedString(@"经度", nil)
#define   root_WO_weidu    NSLocalizedString(@"纬度", nil)
#define   root_WO_banbenhao    NSLocalizedString(@"当前版本:", nil)


#define   root_WO_dianji_huoqu    NSLocalizedString(@"点击获取", nil)
#define   root_WO_jieneng    NSLocalizedString(@"节约标准煤", nil)
#define   root_WO_C02    NSLocalizedString(@"CO2减排", nil)
#define   root_WO_SO2   NSLocalizedString(@"SO2减排", nil)

#define   root_FU_gaisu    NSLocalizedString(@"概述", nil)
#define   root_FU_fuwu_jieshao    NSLocalizedString(@"服务介绍", nil)
#define   root_FU_tigongshang    NSLocalizedString(@"提供商:", nil)
#define   root_FU_shiyong_quyu    NSLocalizedString(@"使用区域:", nil)
#define   root_FU_jiage    NSLocalizedString(@"价格:", nil)
#define   root_FU_lianxi_fangshi    NSLocalizedString(@"联系方式:", nil)

#define   root_shifou_shanchu_shebei    NSLocalizedString(@"是否确定删除设备", nil)

#define root_shanchu_chenggong      NSLocalizedString(@"删除成功", nil)
#define root_shanchu_shibai     NSLocalizedString(@"系统错误，删除失败", nil)

#define root_Ppv     NSLocalizedString(@"Ppv", nil)
#define root_Puser     NSLocalizedString(@"Puser", nil)
#define root_Pgrid     NSLocalizedString(@"Pgrid", nil)

#define root_Revenue     NSLocalizedString(@"Revenue", nil)
#define root_todayPV     NSLocalizedString(@"todayPV", nil)
#define root_PpvN     NSLocalizedString(@"PpvN", nil)

#define root_wo_qingkong_message     NSLocalizedString(@"清空", nil)

#define root_wo_qingkong_lishi_shuju     NSLocalizedString(@"是否清空历史数据", nil)
#define root_wo_qingkong_shuju     NSLocalizedString(@"清空历史数据", nil)
#define root_wo_qingkong_tubiao_shuliang     NSLocalizedString(@"清空APP图标标记数量", nil)

#define root_wenti_leirong    NSLocalizedString(@"问题内容:", nil)

//配置WIFI
#define root_peizhi_shinewifi    NSLocalizedString(@"配置ShineWifi", nil)
#define root_peizhi_shinewifi_yi    NSLocalizedString(@"ShineWifi提示一", nil)
#define root_peizhi_shinewifi_er    NSLocalizedString(@"ShineWifi提示二", nil)
#define root_peizhi_shinewifi_name    NSLocalizedString(@"ShineWifi输入路由器", nil)
#define root_peizhi_shinewifi_mima    NSLocalizedString(@"ShineWifi密码", nil)
#define root_peizhi_shinewifi_shuru_mima   NSLocalizedString(@"ShineWifi输入路由器密码", nil)
#define root_peizhi_shinewifi_xiugai_mima   NSLocalizedString(@"ShineWifi修改密码", nil)
#define root_peizhi_shinewifi_xin_mima   NSLocalizedString(@"ShineWifi新密码", nil)
#define root_peizhi_shinewifi_shuru_wifi_mima   NSLocalizedString(@"请输入Wifi密码", nil)
#define root_peizhi_shinewifi_shuru_chaxun_xinxi   NSLocalizedString(@"查询采集器信息", nil)
#define root_peizhi_shinewifi_xuliehao   NSLocalizedString(@"序列号", nil)
#define root_peizhi_shinewifi_jiaoyanma   NSLocalizedString(@"shinewifi校验码", nil)
#define root_peizhi_shinewifi_E  NSLocalizedString(@"配置ShineWifiE", nil)

#define root_peizhi_shinewifi_E_shaomiao   NSLocalizedString(@"扫描设备和设置路由器", nil)
#define root_peizhi_shinewifi_E_mingzi   NSLocalizedString(@"ShineWifiE名字", nil)
#define root_peizhi_shinewifi_peizhi_tishi   NSLocalizedString(@"配置提示", nil)


#define root_dianzhan_xuanzhe   NSLocalizedString(@"Choice", nil)
#define root_dianzhan_bianji   NSLocalizedString(@"编辑", nil)

#define root_chuneng_fangdianliang   NSLocalizedString(@"储能放电量", nil)

#define root_new   NSLocalizedString(@"新", nil)
#define root_tuijian  NSLocalizedString(@"推荐", nil)

#define root_NBQ_shidian_dianya  NSLocalizedString(@"市电电压", nil)

#define root_yonghu_xieyi  NSLocalizedString(@"用户协议1", nil)
#define root_xuanze_yonghu_xieyi  NSLocalizedString(@"选择用户协议", nil)
#define  root_tianjia_1      NSLocalizedString(@"添加1", nil)
#define  root_lianjie_luyouqi      NSLocalizedString(@"连接路由器2", nil)

#define  root_shuaxin_liebiao     NSLocalizedString(@"刷新设备列表", nil)
#define  root_demo     NSLocalizedString(@"示例", nil)
#define  root_dadianhua     NSLocalizedString(@"拨打电话", nil)

#define  root_huanSuan_danwei     NSLocalizedString(@"换算单位", nil)
#define  root_tupian_fangda     NSLocalizedString(@"点击图片放大", nil)

#define  root_tianjia_dianzhan_chenggong     NSLocalizedString(@"添加电站成功", nil)
#define  root_tianjia_dianzhan_chongfu     NSLocalizedString(@"当前用户下电站名重复", nil)
#define  root_tianjia_dianzhan_chaochu     NSLocalizedString(@"超出用户限制电站数量", nil)
#define  root_tianjia_dianzhan_guojia     NSLocalizedString(@"国家名出错", nil)
#define  root_tianjia_dianzhan_xinxi     NSLocalizedString(@"添加信息出错", nil)

#define  root_haimei_jiejue_wenti     NSLocalizedString(@"还没有解决您的问题", nil)
#define  root_xiang_kefu_tiwen     NSLocalizedString(@"向客服提问", nil)


#define  root_ziliao_zhongxin     NSLocalizedString(@"资料中心", nil)
#define  root_shipin_xitong     NSLocalizedString(@"视频系统", nil)
#define  root_changjian_wenti     NSLocalizedString(@"常见问题", nil)
#define  root_shouce     NSLocalizedString(@"手册", nil)
#define  root_gongsi_guanwang     NSLocalizedString(@"公司官网", nil)

#define  root_gongsi_neirong     NSLocalizedString(@"视频内容", nil)
#define  root_changjian_wenti_neirong     NSLocalizedString(@"常见问题内容", nil)
#define  root_shouce_neirong     NSLocalizedString(@"手册内容", nil)
#define  root_gongsi_guanwang_neirong     NSLocalizedString(@"公司官网内容", nil)
#define  root_huancun     NSLocalizedString(@"缓存", nil)
#define  root_huancun_liebiao     NSLocalizedString(@"缓存列表", nil)
#define  root_quanxuan     NSLocalizedString(@"全选", nil)
#define  root_queding_shanchu_shiping     NSLocalizedString(@"确定删除视频", nil)
#define  root_shiping_huancun_tishi     NSLocalizedString(@"视频缓存提示", nil)
#define  root_xiangguan_shiping     NSLocalizedString(@"相关视频", nil)
#define  root_wifi_tishi     NSLocalizedString(@"wifi提示", nil)
#define  root_huancun_chenggong     NSLocalizedString(@"缓存成功", nil)
#define  root_shifou_baocun_shiping    NSLocalizedString(@"是否保存视频", nil)
#define  root_fuwuqi_bu_pipei    NSLocalizedString(@"服务器与所属国家不匹配", nil)

#define  root_wifi_peizhi    NSLocalizedString(@"ShineWiFi配置", nil)

#define  root_wei_kaiqi_dingwei    NSLocalizedString(@"未开启定位服务", nil)
#define  root_tiaozhuan_jiemian_shezhi    NSLocalizedString(@"是否跳转界面进行设置", nil)

#define  root_wifi_tiaozhuan_tishi    NSLocalizedString(@"wifi页面跳转提示", nil)
#define  root_wifi_lianjie_ok    NSLocalizedString(@"wifi连接成功", nil)
#define  root_wifi_lianjie_failed    NSLocalizedString(@"wifi连接失败", nil)
#define  root_wifi_kandeng    NSLocalizedString(@"wifi看灯", nil)
#define  root_wifi_chenggong_xinxi    NSLocalizedString(@"wifi提示成功信息", nil)
#define  root_wifi_shibai_xinxi    NSLocalizedString(@"wifi提示失败信息", nil)
#define  root_wifi_shibai_xinxi_1    NSLocalizedString(@"wifi提示失败信息1", nil)
#define  root_wifi_shibai_xinxi_2    NSLocalizedString(@"wifi提示失败信息2", nil)
#define  root_wifi_chongxin_peizhi    NSLocalizedString(@"wifi重新配置", nil)

#define  root_yuan_mima_cuowu  NSLocalizedString(@"原密码错误", nil)

#define  root_fuwuqi_cuowu_tishi    NSLocalizedString(@"2服务器错误提示", nil)
#define  root_fuwuqi_cuowu_tishi_2    NSLocalizedString(@"4服务器错误提示2", nil)

#define  root_caijiqi_cuowu_tishi    NSLocalizedString(@"3采集器10位提示", nil)

#define  root_shijian      NSLocalizedString(@"4时间", nil)
#define  root_shuzhi      NSLocalizedString(@"5数据", nil)
#define  root_riqi      NSLocalizedString(@"6日期", nil)
#define  root_zhanghu_meiyou_quanxian      NSLocalizedString(@"7你的账号没有操作权限", nil)
#define  root_shanghua_chakan_shuju      NSLocalizedString(@"8上滑查看详细数据", nil)
#define  root_xiahua_chakan_quxiantu      NSLocalizedString(@"9下滑查看曲线图", nil)
#define  root_budai_guojiahao      NSLocalizedString(@"10填入不带国家代码的手机号", nil)
#define  root_new_wifi_tishi_1_hongdeng      NSLocalizedString(@"11新wifi看灯提示1", nil)
#define  root_new_wifi_tishi_1_hongdeng_yuanyin      NSLocalizedString(@"12新wifi看灯提示1原因", nil)
#define  root_new_wifi_tishi_2_lvdeng      NSLocalizedString(@"13新wifi看灯提示2绿灯", nil)
#define  root_new_wifi_tishi_2_lvdeng_yuanyin      NSLocalizedString(@"14新wifi看灯提示2绿灯原因", nil)
#define  root_new_wifi_tishi_3_landeng      NSLocalizedString(@"15新wifi看灯提示3蓝灯", nil)
#define  root_new_wifi_tishi_3_landeng_yuanyin      NSLocalizedString(@"16新wifi看灯提示3蓝灯原因", nil)
#define  root_tongguo_shoujihao     NSLocalizedString(@"17通过手机号", nil)
#define  root_saomiao_sn    NSLocalizedString(@"18扫描采集器序列号", nil)
#define  root_shoujihao_buneng_kong    NSLocalizedString(@"19手机号不能为空", nil)
#define  root_mima_buneng_weikong    NSLocalizedString(@"20密码不能为空", nil)
#define  root_shuru_duanxin_jiaoyanma    NSLocalizedString(@"21请输入短信验证码", nil)
#define  root_yanzhengma_cuowu    NSLocalizedString(@"22验证码错误", nil)
#define  root_fasong_yanzhengma    NSLocalizedString(@"23发送验证码", nil)
#define  root_yijian_jianzhan   NSLocalizedString(@"24一键建站", nil)
#define  root_tiaoguo   NSLocalizedString(@"25跳过", nil)
#define  root_shanghua_chakan_xianxi_shuju   NSLocalizedString(@"26上滑查看详细数据", nil)
#define  root_guoji_quhao_cuowu  NSLocalizedString(@"27国际区号错误", nil)
#define  root_shouji_geshi_cuowu NSLocalizedString(@"28手机号格式错误", nil)
#define  root_shouji_yanzhengma_shixiao NSLocalizedString(@"29短信验证码请求已经失效", nil)
#define  root_fasongduanxin_yanzhengma_buchenggong NSLocalizedString(@"30发送短信验证码不成功", nil)
#define  root_gaishoujihao_meiyou_zhuce_yonghu NSLocalizedString(@"31该手机号没有注册用户", nil)
#define  root_gaishoujihao_heyanzhengma_bupipei NSLocalizedString(@"32手机号和验证码不匹配", nil)
#define  root_xiugai_mima_shibai NSLocalizedString(@"33修改密码失败", nil)
#define  root_budai_guojia_daima NSLocalizedString(@"34输入不带国家代码的手机号", nil)
#define  root_tongguo_youxiang     NSLocalizedString(@"35通过邮箱", nil)
#define  root_qingshuru_zhengque_jiaoyanma     NSLocalizedString(@"36请输入正确的手机校验码", nil)
#define  root_xiugai_mima_chenggong     NSLocalizedString(@"37修改密码成功", nil)

#define  root_PCS_guangfu    NSLocalizedString(@"38太阳能", nil)
#define  root_PCS_chunengji    NSLocalizedString(@"39储能机", nil)
#define  root_PCS_nibianqi   NSLocalizedString(@"40逆变器", nil)
#define  root_PCS_dianwang   NSLocalizedString(@"41电网", nil)
#define  root_PCS_dianyuan   NSLocalizedString(@"42电池", nil)
#define  root_PCS_fuzhai   NSLocalizedString(@"43负载", nil)
#define  root_PCS_danwei  NSLocalizedString(@"44单位", nil)
#define  root_PCS_guangfu_1  NSLocalizedString(@"45第一路光伏功率", nil)
#define  root_PCS_guangfu_2  NSLocalizedString(@"46第二路光伏功率", nil)
#define  root_PCS_chongdian_1  NSLocalizedString(@"47第一路光伏充电功率", nil)
#define  root_PCS_chongdian_2  NSLocalizedString(@"48第二路光伏充电功率", nil)
#define  root_PCS_dianchi_baifenbi  NSLocalizedString(@"49电池百分比", nil)
#define  root_PCS_dianwang_chongdian_gonglv  NSLocalizedString(@"50电网充电功率", nil)
#define  root_PCS_fuzai_gonglv  NSLocalizedString(@"51负载功率", nil)
#define  root_PCS_to_dianwang  NSLocalizedString(@"52输送电网功率", nil)
#define  root_PCS_from_dianwang  NSLocalizedString(@"53电网输入功率", nil)
#define  root_PCS_fangdian_gonglv  NSLocalizedString(@"54放电功率", nil)
#define  root_jinggong_yijianjianzhan_yonghu  NSLocalizedString(@"55仅供“一键建站”注册用户使用", nil)
#define  root_shoujihao_geshi_cuowu  NSLocalizedString(@"56手机号格式错误", nil)
#define  root_shuru_shiyiwei_shoujihao  NSLocalizedString(@"57输入11位手机号", nil)

#define  root_nengyuan_gailan  NSLocalizedString(@"58能源概览", nil)
#define  root_guangfu_chanchu  NSLocalizedString(@"59光伏产出", nil)
#define  root_guangfu_chanchu_1  NSLocalizedString(@"591光伏产出", nil)
#define  root_nengyuan_chanchu NSLocalizedString(@"60能源产出", nil)
#define  root_nengyuan_chanch_1 NSLocalizedString(@"601能源产出", nil)
#define  root_dianwang_xiaohao   NSLocalizedString(@"61电网消耗", nil)
#define  root_yongdian_xiaohao   NSLocalizedString(@"62用电消耗", nil)
#define  root_yongdian_xiaohao_1   NSLocalizedString(@"621用电消耗", nil)


#define  root_dangri  NSLocalizedString(@"63当日", nil)
#define  root_leiji  NSLocalizedString(@"64累计", nil)
#define  root_nengyuan_chanhao  NSLocalizedString(@"65能源产耗", nil)
#define  root_zong_yongdian  NSLocalizedString(@"66总用电", nil)
#define  root_chuneng_nengyuan  NSLocalizedString(@"67储能能源", nil)
#define  root_mianban_dianliang  NSLocalizedString(@"68面板电量", nil)
#define  root_chuneng_congfang_xinxi  NSLocalizedString(@"69储能充放电信息", nil)
#define  root_shishi_SOC  NSLocalizedString(@"70实时SOC", nil)
#define  root_gongju  NSLocalizedString(@"71工具", nil)
#define  root_wufa_chakan_weilai_shuju  NSLocalizedString(@"72无法查看未来数据", nil)


//翻译后1
#define  root_daichuli  NSLocalizedString(@"73待处理", nil)
#define  root_chulizhong  NSLocalizedString(@"74处理中", nil)
#define  root_yichuli  NSLocalizedString(@"75已处理", nil)
#define  root_daigengjin  NSLocalizedString(@"76待跟进", nil)
#define  root_xiangguang_wenti_miaoshu  NSLocalizedString(@"77请输入相关问题的详细描述", nil)
#define  root_dangqian_fuwuqi_dizhi  NSLocalizedString(@"78当前服务器地址:", nil)
#define  root_dianji_huoqu_fuwuqi  NSLocalizedString(@"79点击获取服务器地址", nil)
#define  root_huoqu_wufuqi_buchenggong  NSLocalizedString(@"80获取服务器地址不成功", nil)
#define  root_shuru_zhengque_youxiang_geshi  NSLocalizedString(@"81请输入正确邮箱格式", nil)
#define  root_shoujihao  NSLocalizedString(@"82手机号:", nil)
#define  root_youxiang  NSLocalizedString(@"83邮箱:", nil)
#define  root_chongdian_shineng  NSLocalizedString(@"84充电使能", nil)
#define  root_chongdian_shijianduan  NSLocalizedString(@"85充电时间段", nil)
#define  root_chongdian_dianchi_soc  NSLocalizedString(@"86充电电池SOC设置", nil)
#define  root_shezhi_shidian_dianya_xiaxian  NSLocalizedString(@"87设置市电电压下限", nil)
#define  root_shineng  NSLocalizedString(@"88使能", nil)
#define  root_jinzhi  NSLocalizedString(@"89禁止", nil)
#define  root_tijiao_wenti  NSLocalizedString(@"90提交问题", nil)

#define  root_shuru_yizhong_lianxi_fangshi  NSLocalizedString(@"91至少输入一种联系方式", nil)
#define  root_shangchuan_sanzhang_tupian  NSLocalizedString(@"92最多上传3张图片", nil)
#define  root_xuanzhe_lianxi_fangshi  NSLocalizedString(@"93选择联系方式", nil)
#define  root_shouji_meiyou_yanzheng  NSLocalizedString(@"94您的手机号还未验证", nil)
#define  root_youxiang_meiyou_yanzheng  NSLocalizedString(@"95您的邮箱还未验证", nil)
#define  root_yanzheng_zhuce_shoujihao  NSLocalizedString(@"96请验证注册时填写的手机号码", nil)
#define  root_yanzheng_yonghu_shoujihao  NSLocalizedString(@"97验证用户手机号码", nil)
#define  root_yanzheng_yonghu_youxiang  NSLocalizedString(@"98验证用户邮箱", nil)
#define  root_zhuce_tianxie_shoujihao  NSLocalizedString(@"99您注册时填写的手机号是", nil)
#define  root_guanbi_wenti  NSLocalizedString(@"100关闭问题", nil)
#define  root_huifu_jilu  NSLocalizedString(@"101回复记录", nil)
#define  root_shifou_guanbi_wenti  NSLocalizedString(@"102是否关闭问题", nil)
#define  root_caozuo_chenggong  NSLocalizedString(@"103操作成功", nil)

#define  root_yanzheng_shouji  NSLocalizedString(@"104请验证您的手机号码", nil)
#define  root_yanzheng_youxiang  NSLocalizedString(@"105请验证您的邮箱地址", nil)
#define  root_wifi_xinhao_tishi  NSLocalizedString(@"106wifi信号强度提示", nil)
#define  root_wifi_lianjie_luyouqi  NSLocalizedString(@"107wifi连接路由器", nil)
#define  root_wifi_tishi_2  NSLocalizedString(@"108wifi提示2", nil)
#define  root_wifi_tishi_3  NSLocalizedString(@"109wifi提示3", nil)

#define  root_5000_dianchi_fangdian  NSLocalizedString(@"110电池放电", nil)
#define  root_5000_pv_chongdian  NSLocalizedString(@"111PV充电", nil)
#define  root_5000_ac_chongdian  NSLocalizedString(@"112AC充电", nil)
#define  root_5000_lianhe_chongdian  NSLocalizedString(@"113联合充电模式", nil)
#define  root_5000_pvchong_dianchifang  NSLocalizedString(@"114PV充电和电池带载", nil)
#define  root_5000_pvchong_acfang  NSLocalizedString(@"115PV充电和市电旁路带载", nil)
#define  root_5000_acchong_acfang  NSLocalizedString(@"116AC充电和市电旁路带载", nil)
#define  root_5000_lianhechong_acfang  NSLocalizedString(@"117联合充电和市电旁路带载", nil)
#define  root_5000_ac_fang  NSLocalizedString(@"118市电旁路带载", nil)

#define  root_5000xianqing_dianchi_dianya  NSLocalizedString(@"119电池电压", nil)
#define  root_5000xianqing_PV_dianya  NSLocalizedString(@"120PV1/PV2电压", nil)
#define  root_5000xianqing_PV_dianliu  NSLocalizedString(@"121PV1/PV2充电电流", nil)
#define  root_5000xianqing_zongChongdian_dianliu  NSLocalizedString(@"122总充电电流", nil)
#define  root_5000xianqing_ac_shuru  NSLocalizedString(@"123AC输入电压和频率", nil)
#define  root_5000xianqing_ac_shuchu  NSLocalizedString(@"124AC输出电压和频率", nil)
#define  root_5000xianqing_fuzai_gonglv  NSLocalizedString(@"125负载功率", nil)
#define  root_5000xianqing_fuzai_baifengbi  NSLocalizedString(@"126负载百分比", nil)

#define  root_jinri_shouyi  NSLocalizedString(@"127今日收益", nil)
#define  root_zong_shouyi  NSLocalizedString(@"128总收益", nil)

#define  root_5000Control_129  NSLocalizedString(@"129AC输出源", nil)
#define  root_5000Control_130  NSLocalizedString(@"130充电源", nil)
#define  root_5000Control_131  NSLocalizedString(@"131市电输出", nil)
#define  root_5000Control_132  NSLocalizedString(@"132市电充电", nil)
#define  root_5000Control_133  NSLocalizedString(@"133光伏接入模式", nil)
#define  root_5000Control_134  NSLocalizedString(@"134AC输入模式", nil)
#define  root_5000Control_135  NSLocalizedString(@"135AC输出电压", nil)
#define  root_5000Control_136  NSLocalizedString(@"136AC输出频率", nil)
#define  root_5000Control_137  NSLocalizedString(@"137过载重启", nil)
#define  root_5000Control_138  NSLocalizedString(@"138过温重启", nil)
#define  root_5000Control_139  NSLocalizedString(@"139蜂鸣器", nil)
#define  root_5000Control_140  NSLocalizedString(@"140最大充电电流", nil)
#define  root_5000Control_141  NSLocalizedString(@"141电池低压点", nil)
#define  root_5000Control_142  NSLocalizedString(@"142系统时间", nil)
#define  root_5000Control_143  NSLocalizedString(@"143电池类型", nil)

#define  root_5000Control_144  NSLocalizedString(@"144光伏优先", nil)
#define  root_5000Control_145  NSLocalizedString(@"145光伏和市电", nil)
#define  root_5000Control_146  NSLocalizedString(@"146仅光伏", nil)
#define  root_5000Control_147  NSLocalizedString(@"147电池优先", nil)
#define  root_5000Control_148  NSLocalizedString(@"148市电优先", nil)
#define  root_5000Control_149  NSLocalizedString(@"149独立", nil)
#define  root_5000Control_150  NSLocalizedString(@"150并联", nil)
#define  root_5000Control_151  NSLocalizedString(@"151重启", nil)
#define  root_5000Control_152  NSLocalizedString(@"152不重启", nil)
#define  root_5000Control_153  NSLocalizedString(@"153切换到市电", nil)
#define  root_5000Control_154  NSLocalizedString(@"154锂电池", nil)
#define  root_5000Control_155  NSLocalizedString(@"155铅酸电池", nil)
#define  root_5000Control_156  NSLocalizedString(@"156自定义铅酸电池", nil)

#define  root_5000Chart_157  NSLocalizedString(@"157PV1功率", nil)
#define  root_5000Chart_158  NSLocalizedString(@"158PV2功率", nil)
#define  root_5000Chart_159  NSLocalizedString(@"159PV1电压", nil)
#define  root_5000Chart_160  NSLocalizedString(@"160PV2电压", nil)
#define  root_5000Chart_161  NSLocalizedString(@"161电池的SOC", nil)
#define  root_5000Chart_162  NSLocalizedString(@"162电池的电压", nil)
#define  root_5000Chart_163  NSLocalizedString(@"163负载的功率", nil)
#define  root_5000Chart_164  NSLocalizedString(@"164负载的电压", nil)
#define  root_5000Chart_165  NSLocalizedString(@"165市电电压", nil)
#define  root_5000Chart_166  NSLocalizedString(@"166Pv当天充电量", nil)
#define  root_5000Chart_167  NSLocalizedString(@"167AC当天充电量", nil)
#define  root_5000Chart_168  NSLocalizedString(@"168电池当天充电量", nil)
#define  root_5000Chart_169  NSLocalizedString(@"169电池当天放电量", nil)
#define  root_5000Chart_170  NSLocalizedString(@"170Pv的总充电量", nil)
#define  root_5000Chart_171  NSLocalizedString(@"171AC的总充电量", nil)
#define  root_5000Chart_172  NSLocalizedString(@"172电池总的充电量", nil)
#define  root_5000Chart_173  NSLocalizedString(@"173电池总的放电量", nil)

#define  root_5000Chart_174  NSLocalizedString(@"174充电量", nil)

#define  root_5000Chart_175  NSLocalizedString(@"175光伏储能", nil)
#define  root_5000Chart_176  NSLocalizedString(@"176电网储能", nil)
#define  root_5000Chart_177  NSLocalizedString(@"177电池放电", nil)
#define  root_5000Chart_178  NSLocalizedString(@"178AC旁路放电", nil)
#define  root_5000Chart_179  NSLocalizedString(@"179请选择采集器类型", nil)

#define  root_Device_head_180  NSLocalizedString(@"180当前功率", nil)
#define  root_Device_head_181  NSLocalizedString(@"181装机容量", nil)
#define  root_Device_head_182  NSLocalizedString(@"182今日收益", nil)
#define  root_Device_head_183  NSLocalizedString(@"183累计收益", nil)

#define  root_Device_head_184  NSLocalizedString(@"184日充电量", nil)
#define  root_Device_head_185  NSLocalizedString(@"185总充电量", nil)
#define  root_Device_head_186  NSLocalizedString(@"186在线", nil)
#define  root_Device_head_187 NSLocalizedString(@"187视在功率", nil)
#define  root_Device_head_188 NSLocalizedString(@"188暂无数据", nil)

#define  root_usbTowifi_189 NSLocalizedString(@"189额定功率", nil)
#define  root_usbTowifi_190 NSLocalizedString(@"190警告", nil)

#define  root_pay_191 NSLocalizedString(@"191请输入备注信息", nil)

#define  root_MIX_192 NSLocalizedString(@"192第一路PV电压", nil)
#define  root_MIX_193 NSLocalizedString(@"193第一路PV功率", nil)
#define  root_MIX_194 NSLocalizedString(@"194第二路PV电压", nil)
#define  root_MIX_195 NSLocalizedString(@"195第二路PV功率", nil)
#define  root_MIX_196 NSLocalizedString(@"196电池电压", nil)
#define  root_MIX_197 NSLocalizedString(@"197电网电压", nil)
#define  root_MIX_198 NSLocalizedString(@"198电网频率", nil)
#define  root_MIX_199 NSLocalizedString(@"199EPS电压", nil)
#define  root_MIX_200 NSLocalizedString(@"200EPS频率", nil)

#define  root_MIX_201 NSLocalizedString(@"201等待模式", nil)
#define  root_MIX_202 NSLocalizedString(@"202自检模式", nil)
#define  root_MIX_203 NSLocalizedString(@"203保留模式", nil)
#define  root_MIX_204 NSLocalizedString(@"204SysFault模式", nil)
#define  root_MIX_205 NSLocalizedString(@"205Flash模式", nil)
#define  root_MIX_206 NSLocalizedString(@"206并网工作中", nil)
#define  root_MIX_207 NSLocalizedString(@"207离网工作中", nil)
#define  root_MIX_208 NSLocalizedString(@"208负载优先", nil)
#define  root_MIX_209 NSLocalizedString(@"209电池优先", nil)
#define  root_MIX_210 NSLocalizedString(@"210电网优先", nil)

#define  root_MIX_211 NSLocalizedString(@"211用电功率", nil)
#define  root_MIX_212 NSLocalizedString(@"212并网功率", nil)
#define  root_MIX_213 NSLocalizedString(@"213馈回电网", nil)
#define  root_MIX_214 NSLocalizedString(@"214电网取电", nil)
#define  root_MIX_215 NSLocalizedString(@"215来自电池", nil)
#define  root_MIX_216 NSLocalizedString(@"216自发自用", nil)
#define  root_MIX_217 NSLocalizedString(@"217馈回电网", nil)
#define  root_MIX_218 NSLocalizedString(@"218电池能源", nil)
#define  root_MIX_219 NSLocalizedString(@"219电池充放电信息", nil)
#define  root_MIX_220 NSLocalizedString(@"220能量优先级", nil)
#define  root_MIX_221 NSLocalizedString(@"221开关", nil)
#define  root_MIX_222 NSLocalizedString(@"222时间段", nil)
#define  root_MIX_223 NSLocalizedString(@"223点击选择", nil)
#define  root_MIX_224 NSLocalizedString(@"224选择设置值", nil)
#define  root_MIX_225 NSLocalizedString(@"225请选择", nil)
#define  root_MIX_226 NSLocalizedString(@"226升级中", nil)
#define  root_MIX_227 NSLocalizedString(@"227放电停止SOC", nil)
#define  root_MIX_228 NSLocalizedString(@"228充电停止SOC", nil)
#define  root_MIX_229 NSLocalizedString(@"229电池充电功率", nil)
#define  root_MIX_230 NSLocalizedString(@"230PV总电量", nil)
#define  root_MIX_231 NSLocalizedString(@"231PV今日电量", nil)
#define  root_MIX_232 NSLocalizedString(@"232电池今日充电量", nil)
#define  root_MIX_233 NSLocalizedString(@"233电池总充电量", nil)
#define  root_MIX_234 NSLocalizedString(@"234电池今日放电量", nil)
#define  root_MIX_235 NSLocalizedString(@"235电池总放电量", nil)
#define  root_MIX_236 NSLocalizedString(@"236逆变器功率", nil)
#define  root_MIX_237 NSLocalizedString(@"237用户侧功率", nil)
#define  root_MIX_238 NSLocalizedString(@"238电网侧功率", nil)

#define  root_ME_239 NSLocalizedString(@"239配置WIFI采集器", nil)
#define  root_ME_240 NSLocalizedString(@"240本地调试工具", nil)
#define  root_ME_241 NSLocalizedString(@"241工具箱", nil)
#define  root_scan_242 NSLocalizedString(@"242扫描获取WiFi名称", nil)

#define  root_device_243 NSLocalizedString(@"243电流", nil)
#define  root_device_244 NSLocalizedString(@"244电压", nil)
#define  root_device_245 NSLocalizedString(@"245AC功率", nil)

#define  root_device_246 NSLocalizedString(@"246命令参数错误", nil)
#define  root_device_247 NSLocalizedString(@"247有功功率错误", nil)
#define  root_device_248 NSLocalizedString(@"248功率因数错误", nil)
#define  root_device_249 NSLocalizedString(@"249设置是否存储PF命令", nil)
#define  root_device_250 NSLocalizedString(@"250设置市电电压上限", nil)
#define  root_device_251 NSLocalizedString(@"251设置市电电压下限", nil)
#define  root_device_252 NSLocalizedString(@"252离网使能", nil)
#define  root_device_253 NSLocalizedString(@"253离网频率", nil)
#define  root_device_254 NSLocalizedString(@"254离网电压", nil)
#define  root_device_255 NSLocalizedString(@"255请输入", nil)
#define  root_device_256 NSLocalizedString(@"256容性", nil)
#define  root_device_257 NSLocalizedString(@"257请选择设置值", nil)
#define  root_device_258 NSLocalizedString(@"258请同时设置起始和结束时间", nil)
#define  root_device_259 NSLocalizedString(@"259感性", nil)

#define  root_device_260 NSLocalizedString(@"260光伏功率", nil)
#define  root_device_261 NSLocalizedString(@"261取电功率", nil)
#define  root_device_262 NSLocalizedString(@"262馈电功率", nil)

#define  root_Energy_263 NSLocalizedString(@"263电网取电", nil)
#define  root_Energy_264 NSLocalizedString(@"264来自", nil)

#define  root_device_265 NSLocalizedString(@"265充电功率", nil)
#define  root_device_266 NSLocalizedString(@"266放电功率", nil)

//MAX本地调试
#define  root_MAX_267 NSLocalizedString(@"267最后更新时间为", nil)
#define  root_MAX_268 NSLocalizedString(@"268自动刷新", nil)
#define  root_MAX_269 NSLocalizedString(@"269WiFi名称为", nil)

#define  root_MAX_270 NSLocalizedString(@"270是否跳转连接WiFi", nil)
#define  root_MAX_271 NSLocalizedString(@"271连接", nil)
#define  root_MAX_272 NSLocalizedString(@"272PV电压/电流", nil)
#define  root_MAX_273 NSLocalizedString(@"273组串电压/电流", nil)
#define  root_MAX_274 NSLocalizedString(@"274AC电压/频率/电流/功率", nil)
#define  root_MAX_275 NSLocalizedString(@"275PID电压/电流", nil)
#define  root_MAX_276 NSLocalizedString(@"276内部参数", nil)
#define  root_MAX_277 NSLocalizedString(@"277关于本机", nil)
#define  root_MAX_278 NSLocalizedString(@"278未连接WiFi模块", nil)
#define  root_MAX_279 NSLocalizedString(@"279请跳转连接WiFi", nil)
#define  root_MAX_280 NSLocalizedString(@"280停止刷新", nil)
#define  root_MAX_281 NSLocalizedString(@"281设备控制", nil)
#define  root_MAX_282 NSLocalizedString(@"282重置密码", nil)
#define  root_MAX_283 NSLocalizedString(@"283设置配置", nil)
#define  root_MAX_284 NSLocalizedString(@"284参数设置", nil)
#define  root_MAX_285 NSLocalizedString(@"285智能检测", nil)
#define  root_MAX_286 NSLocalizedString(@"286高级设置", nil)
#define  root_MAX_287 NSLocalizedString(@"287未获取控制密码", nil)
#define  root_MAX_288 NSLocalizedString(@"288请登录OSS系统获取密码", nil)
#define  root_MAX_289 NSLocalizedString(@"289密码错误,请验证密码或重置密码.", nil)
#define  root_MAX_290 NSLocalizedString(@"290请先读取故障信息", nil)
#define  root_MAX_291 NSLocalizedString(@"291设备信息", nil)
#define  root_MAX_292 NSLocalizedString(@"292数据读取失败,请重试或检查WiFi连接", nil)
#define  root_MAX_293 NSLocalizedString(@"293检查", nil)
#define  root_MAX_294 NSLocalizedString(@"294获取控制密码", nil)
#define  root_MAX_295 NSLocalizedString(@"295OSS账户", nil)
#define  root_MAX_296 NSLocalizedString(@"296设置密码", nil)
#define  root_MAX_297 NSLocalizedString(@"297设置", nil)
#define  root_MAX_298 NSLocalizedString(@"298请确认手机是否已连接互联网", nil)
#define  root_MAX_299 NSLocalizedString(@"299是否需要切换网络", nil)
#define  root_MAX_300 NSLocalizedString(@"300切换", nil)
#define  root_MAX_301 NSLocalizedString(@"301请添加设置密码", nil)
#define  root_MAX_302 NSLocalizedString(@"302本地调试工具密码为", nil)
#define  root_MAX_303 NSLocalizedString(@"303设置成功", nil)
#define  root_MAX_304 NSLocalizedString(@"304登录成功", nil)
#define  root_MAX_305 NSLocalizedString(@"305并网倒计时", nil)
#define  root_MAX_306 NSLocalizedString(@"306功率百分比", nil)
#define  root_MAX_307 NSLocalizedString(@"307内部环境温度", nil)
#define  root_MAX_308 NSLocalizedString(@"308Boost温度", nil)
#define  root_MAX_309 NSLocalizedString(@"309INV温度", nil)
#define  root_MAX_310 NSLocalizedString(@"310PID故障信息", nil)
#define  root_MAX_311 NSLocalizedString(@"311PID状态", nil)
#define  root_MAX_312 NSLocalizedString(@"312厂商信息", nil)
#define  root_MAX_313 NSLocalizedString(@"313机器型号", nil)
#define  root_MAX_314 NSLocalizedString(@"314Model号", nil)
#define  root_MAX_315 NSLocalizedString(@"315固件(外部)版本", nil)
#define  root_MAX_316 NSLocalizedString(@"316固件(内部)版本", nil)
#define  root_MAX_317 NSLocalizedString(@"317AC电压/电流/功率/频率", nil)
#define  root_MAX_318 NSLocalizedString(@"318电压", nil)    //简写
#define  root_MAX_319 NSLocalizedString(@"319电流", nil)    //简写
#define  root_MAX_320 NSLocalizedString(@"320功率", nil)      //简写
#define  root_MAX_321 NSLocalizedString(@"321频率", nil)      //简写
#define  root_MAX_322 NSLocalizedString(@"322刷新", nil)
#define  root_MAX_323 NSLocalizedString(@"323无历史故障", nil)
#define  root_MAX_324 NSLocalizedString(@"324故障码", nil)
#define  root_MAX_325 NSLocalizedString(@"325历史故障", nil)
#define  root_MAX_326 NSLocalizedString(@"326警告码", nil)

//故障翻译
#define  root_MAX_327 NSLocalizedString(@"327通信故障", nil)
#define  root_MAX_328 NSLocalizedString(@"328冗余采样异常保护", nil)
#define  root_MAX_329 NSLocalizedString(@"329主SPS供电异常", nil)
#define  root_MAX_330 NSLocalizedString(@"330AFCI拉弧故障", nil)
#define  root_MAX_331 NSLocalizedString(@"331IGBT驱动错误", nil)
#define  root_MAX_332 NSLocalizedString(@"332AFCI模块检测失败", nil)
#define  root_MAX_333 NSLocalizedString(@"333AC侧继电器异常", nil)
#define  root_MAX_334 NSLocalizedString(@"334CPLD芯片检测异常", nil)
#define  root_MAX_335 NSLocalizedString(@"335BUS电压异常", nil)
#define  root_MAX_336 NSLocalizedString(@"336无电网连接", nil)
#define  root_MAX_337 NSLocalizedString(@"337PV绝缘阻抗低", nil)
#define  root_MAX_338 NSLocalizedString(@"338漏电流过高", nil)
#define  root_MAX_339 NSLocalizedString(@"339输出电流直流分量过高", nil)
#define  root_MAX_340 NSLocalizedString(@"340PV电压过高", nil)
#define  root_MAX_341 NSLocalizedString(@"341电网过欠压保护", nil)
#define  root_MAX_342 NSLocalizedString(@"342电网过欠频保护", nil)

#define  root_MAX_343 NSLocalizedString(@"343风扇异常", nil)
#define  root_MAX_344 NSLocalizedString(@"344DSP与M3版本不一致", nil)
#define  root_MAX_345 NSLocalizedString(@"345防雷器发生故障", nil)
#define  root_MAX_346 NSLocalizedString(@"346NE检测异常，N线、地线之间压差过大", nil)
#define  root_MAX_347 NSLocalizedString(@"347PV1至PV6 短路异常", nil)
#define  root_MAX_348 NSLocalizedString(@"348直流升压驱动异常", nil)
#define  root_MAX_349 NSLocalizedString(@"349组串异常", nil)
#define  root_MAX_350 NSLocalizedString(@"350U盘过流保护", nil)

#define  root_MAX_351 NSLocalizedString(@"351无故障信息", nil)
#define  root_MAX_352 NSLocalizedString(@"352无警告信息", nil)
#define  root_MAX_353 NSLocalizedString(@"353时", nil)

#define  root_MAX_354 NSLocalizedString(@"354最近24小时发电量", nil)
#define  root_MAX_355 NSLocalizedString(@"355最近7天发电量", nil)
#define  root_MAX_356 NSLocalizedString(@"356最近12个月发电量", nil)
#define  root_MAX_357 NSLocalizedString(@"357最近20年发电量", nil)

//单位
#define  root_MAX_358 NSLocalizedString(@"358日", nil)
#define  root_MAX_359 NSLocalizedString(@"359月", nil)
#define  root_MAX_360 NSLocalizedString(@"360年", nil)
#define  root_MAX_361 NSLocalizedString(@"361请填写参数", nil)
#define  root_MAX_362 NSLocalizedString(@"362设置失败,请重新进入页面进行设置", nil)
#define  root_MAX_363 NSLocalizedString(@"363设置失败", nil)
#define  root_MAX_364 NSLocalizedString(@"364请查看设置范围或检查网络连接", nil)
#define  root_MAX_365 NSLocalizedString(@"365发送数据", nil)
#define  root_MAX_366 NSLocalizedString(@"366收到数据", nil)
#define  root_MAX_367 NSLocalizedString(@"367读取数据失败", nil)
#define  root_MAX_368 NSLocalizedString(@"368请重试或检查网络连接", nil)
#define  root_MAX_369 NSLocalizedString(@"369读取值", nil)
#define  root_MAX_370 NSLocalizedString(@"370读取", nil)
#define  root_MAX_371 NSLocalizedString(@"371设置", nil)
#define  root_MAX_372 NSLocalizedString(@"372高", nil)
#define  root_MAX_373 NSLocalizedString(@"373低", nil)
#define  root_MAX_374 NSLocalizedString(@"374设置Model", nil)
#define  root_MAX_375 NSLocalizedString(@"375请添加设置值", nil)
#define  root_MAX_376 NSLocalizedString(@"376读取失败", nil)
#define  root_MAX_377 NSLocalizedString(@"377记忆使能", nil)
#define  root_MAX_378 NSLocalizedString(@"378记忆", nil)

#define  root_MAX_379 NSLocalizedString(@"379电源启动斜率", nil)
#define  root_MAX_380 NSLocalizedString(@"380电源重启斜率", nil)
#define  root_MAX_381 NSLocalizedString(@"381Q(v)切入高压", nil)
#define  root_MAX_382 NSLocalizedString(@"382Q(v)切出高压", nil)
#define  root_MAX_383 NSLocalizedString(@"383Q(v)切入低压", nil)
#define  root_MAX_384 NSLocalizedString(@"384Q(v)切出低压", nil)
#define  root_MAX_385 NSLocalizedString(@"385Q(v)切入功率", nil)
#define  root_MAX_386 NSLocalizedString(@"386Q(v)切出功率", nil)
#define  root_MAX_387 NSLocalizedString(@"387无功曲线切入电压", nil)
#define  root_MAX_388 NSLocalizedString(@"388无功曲线切出电压", nil)
#define  root_MAX_389 NSLocalizedString(@"389检查固件", nil)
#define  root_MAX_390 NSLocalizedString(@"390PF调整值", nil)
#define  root_MAX_391 NSLocalizedString(@"391PF限制负载百分比点", nil)
#define  root_MAX_392 NSLocalizedString(@"392PF限制功率因数", nil)
#define  root_MAX_393 NSLocalizedString(@"393暂不允许设置", nil)
#define  root_MAX_394 NSLocalizedString(@"394不记忆", nil)
#define  root_MAX_395 NSLocalizedString(@"395记忆", nil)
#define  root_MAX_396 NSLocalizedString(@"396开关逆变器", nil)
#define  root_MAX_397 NSLocalizedString(@"397安规功能使能", nil)
#define  root_MAX_398 NSLocalizedString(@"398有功功率百分比", nil)
#define  root_MAX_399 NSLocalizedString(@"399感性载率", nil)
#define  root_MAX_400 NSLocalizedString(@"400容性载率", nil)
#define  root_MAX_401 NSLocalizedString(@"401容性PF", nil)
#define  root_MAX_402 NSLocalizedString(@"402感性PF", nil)
#define  root_MAX_403 NSLocalizedString(@"403PV电压", nil)
#define  root_MAX_404 NSLocalizedString(@"404选择通信波特率", nil)
#define  root_MAX_405 NSLocalizedString(@"405运行PF为1", nil)
#define  root_MAX_406 NSLocalizedString(@"406过频降额起点", nil)
#define  root_MAX_407 NSLocalizedString(@"407频率-负载限制率", nil)
#define  root_MAX_408 NSLocalizedString(@"408Q(v)无功延时", nil)
#define  root_MAX_409 NSLocalizedString(@"409过频降额延时", nil)
#define  root_MAX_410 NSLocalizedString(@"410Q(v)曲线Q最大值", nil)
#define  root_MAX_411 NSLocalizedString(@"411Island使能", nil)
#define  root_MAX_412 NSLocalizedString(@"412风扇检查", nil)
#define  root_MAX_413 NSLocalizedString(@"413电网N线使能", nil)
#define  root_MAX_414 NSLocalizedString(@"414N至GND监测功能使能", nil)
#define  root_MAX_415 NSLocalizedString(@"415非标准电网电压范围使能", nil)
#define  root_MAX_416 NSLocalizedString(@"416指定的规格设置使能", nil)
#define  root_MAX_417 NSLocalizedString(@"417MPPT使能", nil)
#define  root_MAX_418 NSLocalizedString(@"418电源启动/重启斜率", nil)
#define  root_MAX_419 NSLocalizedString(@"419Q(v)切入/切出高压", nil)
#define  root_MAX_420 NSLocalizedString(@"420Q(v)切入/切出低压", nil)
#define  root_MAX_421 NSLocalizedString(@"421Q(v)切入/切出功率", nil)
#define  root_MAX_422 NSLocalizedString(@"422无功曲线切入/切出电压", nil)
#define  root_MAX_423 NSLocalizedString(@"423通信地址", nil)
#define  root_MAX_424 NSLocalizedString(@"424启动电压", nil)
#define  root_MAX_425 NSLocalizedString(@"425启动时间", nil)
#define  root_MAX_426 NSLocalizedString(@"426故障恢复后重启延迟时间", nil)
#define  root_MAX_427 NSLocalizedString(@"427语言", nil)
#define  root_MAX_428 NSLocalizedString(@"428系统一周", nil)
#define  root_MAX_429 NSLocalizedString(@"429AC电压10分钟保护值", nil)
#define  root_MAX_430 NSLocalizedString(@"430PV电压高故障", nil)
#define  root_MAX_431 NSLocalizedString(@"431Modbus版本", nil)
#define  root_MAX_432 NSLocalizedString(@"432PID工作模式", nil)
#define  root_MAX_433 NSLocalizedString(@"433PID开关", nil)
#define  root_MAX_434 NSLocalizedString(@"434PID工作电压", nil)
#define  root_MAX_435 NSLocalizedString(@"435逆变器模块", nil)
#define  root_MAX_436 NSLocalizedString(@"436逆变器经纬度", nil)
#define  root_MAX_437 NSLocalizedString(@"437限制电压低/高", nil)
#define  root_MAX_438 NSLocalizedString(@"438频率限制低/高", nil)

#define  root_MAX_439 NSLocalizedString(@"439并网电压限制低/高", nil)
#define  root_MAX_440 NSLocalizedString(@"440并网频率限制低/高", nil)
#define  root_MAX_441 NSLocalizedString(@"441电压限制时间", nil)
#define  root_MAX_442 NSLocalizedString(@"442频率限制时间", nil)
#define  root_MAX_443 NSLocalizedString(@"443该项暂不能设置,请设置Model.", nil)
#define  root_MAX_444 NSLocalizedString(@"444该项暂不能设置.", nil)
#define  root_MAX_445 NSLocalizedString(@"445智能I-V曲线扫描", nil)
#define  root_MAX_446 NSLocalizedString(@"446故障录波检测", nil)
#define  root_MAX_447 NSLocalizedString(@"447实时录波检测", nil)
#define  root_MAX_448 NSLocalizedString(@"448一键诊断", nil)
#define  root_MAX_449 NSLocalizedString(@"449可远程扫描每路MPPT。", nil)
#define  root_MAX_450 NSLocalizedString(@"450可远程、快速、精确地进行故障定位。", nil)
#define  root_MAX_451 NSLocalizedString(@"451可实时观察逆变器电压电流质量等。", nil)
#define  root_MAX_452 NSLocalizedString(@"452一键检测电站环境信息，包括I-V曲线扫描，电网侧电压波形，THDV以及线路阻抗。", nil)
#define  root_MAX_453 NSLocalizedString(@"453选择一键诊断模块", nil)
#define  root_MAX_454 NSLocalizedString(@"454I-V/P-V曲线", nil)
#define  root_MAX_455 NSLocalizedString(@"455电网电压波形", nil)
#define  root_MAX_456 NSLocalizedString(@"456电网电压谐波(THDV)", nil)
#define  root_MAX_457 NSLocalizedString(@"457电网线路阻抗", nil)
#define  root_MAX_458 NSLocalizedString(@"4581、确保逆变器在运行状态；2、检测过程中会关断逆变器；3、诊断时间预计15分钟", nil)
#define  root_MAX_458_1 NSLocalizedString(@"458_11、确保逆变器在运行状态；2、诊断时间预计", nil)

#define  root_MAX_459 NSLocalizedString(@"459分钟", nil)
#define  root_MAX_460 NSLocalizedString(@"460开始", nil)
#define  root_MAX_461 NSLocalizedString(@"461读取数据中", nil)
#define  root_MAX_462 NSLocalizedString(@"462I-V/P-V 曲线", nil)
#define  root_MAX_463 NSLocalizedString(@"463相阻抗", nil)  //R S T
#define  root_MAX_464 NSLocalizedString(@"464故障序号", nil)
#define  root_MAX_465 NSLocalizedString(@"465波形触发时间", nil)
#define  root_MAX_466 NSLocalizedString(@"466数据读取失败", nil)
#define  root_MAX_467 NSLocalizedString(@"467请重试或检查WiFi连接.", nil)
#define  root_MAX_468 NSLocalizedString(@"468已经是最大显示", nil)
#define  root_MAX_469 NSLocalizedString(@"469显示倍数", nil)
#define  root_MAX_470 NSLocalizedString(@"470波形值", nil)
#define  root_MAX_471 NSLocalizedString(@"471设置ID", nil)
#define  root_MAX_472 NSLocalizedString(@"472请输入故障ID号", nil)
#define  root_MAX_473 NSLocalizedString(@"473请填写曲线显示的倍数", nil)
#define  root_MAX_474 NSLocalizedString(@"474选择故障序号", nil)
#define  root_MAX_475 NSLocalizedString(@"475请填写ID号", nil)
#define  root_MAX_476 NSLocalizedString(@"476请输入正确的ID号", nil)
#define  root_MAX_477 NSLocalizedString(@"477曲线", nil)
#define  root_MAX_478 NSLocalizedString(@"478谐波次数", nil)

#define  root_Device_479 NSLocalizedString(@"479获取密码失败，请重新进入页面", nil)

#define  root_SPF5000_480 NSLocalizedString(@"480离网储能逆变器", nil)



#define  root_5000Chart_481  NSLocalizedString(@"481PV月充电量", nil)
#define  root_5000Chart_482  NSLocalizedString(@"482AC月充电量", nil)
#define  root_5000Chart_483  NSLocalizedString(@"483电池月充电量", nil)
#define  root_5000Chart_484  NSLocalizedString(@"484电池月放电量", nil)
#define  root_5000Chart_485  NSLocalizedString(@"485PV年充电量", nil)
#define  root_5000Chart_486  NSLocalizedString(@"486AC年充电量", nil)
#define  root_5000Chart_487  NSLocalizedString(@"487电池年充电量", nil)
#define  root_5000Chart_488  NSLocalizedString(@"488电池年放电量", nil)
#define  root_Inverter_489  NSLocalizedString(@"489电压", nil)
#define  root_Inverter_490  NSLocalizedString(@"490电流", nil)
#define  root_Inverter_491  NSLocalizedString(@"491功率", nil)

#define  root_MIX_492  NSLocalizedString(@"492防逆流设置", nil)

#define  root_MIX_493  NSLocalizedString(@"493Phase", nil)
#define  root_MAX_494  NSLocalizedString(@"494全选", nil)

#define  root_Device_max_495  NSLocalizedString(@"495有功设置错误", nil)
#define  root_Device_max_496  NSLocalizedString(@"496功率设置错误", nil)

#define  root_MAX_497  NSLocalizedString(@"497有效值", nil)

#define  root_MAX_498  NSLocalizedString(@"498自动获取", nil)
#define  root_MAX_499  NSLocalizedString(@"499手动输入", nil)
#define  root_MAX_500 NSLocalizedString(@"500不获取", nil)
#define  root_MAX_501 NSLocalizedString(@"501选择位置获取方式", nil)
#define  root_MAX_502 NSLocalizedString(@"502客服邮箱", nil)

#define  root_MIX_503 NSLocalizedString(@"503电池自采电压", nil)

#define  root_MAX_504 NSLocalizedString(@"504跳过", nil)


#define  root_oss_505_Status NSLocalizedString(@"505状态", nil)
#define  root_oss_506_leiXing NSLocalizedString(@"506类型", nil)
#define  root_oss_507_chengShi NSLocalizedString(@"507城市", nil)
#define  root_oss_508_zuiHouGenXinShiJian NSLocalizedString(@"508最后更新时间", nil)
#define  root_oss_509_lianJieZhuangTai NSLocalizedString(@"509连接状态", nil)
#define  root_oss_510_yunXingZhuangTai NSLocalizedString(@"510运行状态", nil)


#define  root_oss_511_dianZhanGuanLi NSLocalizedString(@"511电站管理", nil)
#define  root_oss_512_fanHui_dianZhanGuanLi NSLocalizedString(@"512返回电站管理", nil)
#define  root_oss_513_jianZhanShiJian NSLocalizedString(@"513建站日期", nil)
#define  root_oss_514_sheBeiShuLiang NSLocalizedString(@"514设备数量", nil)
#define  root_oss_515_yiJingDaoZuiHouYiYe NSLocalizedString(@"515已经到最后一页", nil)
#define  root_oss_516_zhanShiCanShu NSLocalizedString(@"516展示参数", nil)
#define  root_oss_517_yiXianShiCanShu NSLocalizedString(@"517已显示参数", nil)
#define  root_oss_518_tuoYeKeYiPaiXu NSLocalizedString(@"518拖拽可以排序", nil)
#define  root_oss_519_weiXianShiCanShu NSLocalizedString(@"519未显示参数", nil)
#define  root_oss_520_QuanBuDianZhanLeiJiShuJu NSLocalizedString(@"520全部电站累计数据", nil)
#define  root_oss_521_QuanBuDianZhan_BuNengBianJi NSLocalizedString(@"521全部电站不能编辑", nil)
#define  root_oss_522_bianJiDianZhan NSLocalizedString(@"522编辑电站", nil)

#define  root_oss_523_ShanChuDianZhan NSLocalizedString(@"523删除电站", nil)
#define  root_oss_524_dangqianGongLv NSLocalizedString(@"524当前功率", nil)
#define  root_oss_525_shousuoDianZhang NSLocalizedString(@"525搜索电站", nil)





#endif /* languageNew_h */
